
services:

  gitlab:
    image: 'gitlab/gitlab-ce:nightly'
    container_name: gitlab
    hostname: 'gitlab.corso.local'
    # restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.corso.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 5022
    networks:
      - net-corso-devops
    ports:
      - '9080:80'
      - '5443:443'
      - '5022:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    shm_size: '256m'


volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

networks:
  net-corso-devops:
    driver: bridge